### ISSUE TITLE
What about Charleston?

### ISSUE THREAD

**Issue by robinpaulson** [jevonlongdell/nztides#12]
Apparently a port on the west coast of SI, near Westport.

https://www.linz.govt.nz/sites/default/files/docs/hydro/tidal-info/tide-tables/maj-ports/csv/Charleston%202016.csv

Maybe a recent addition to LINz data files?

**Comment by robinpaulson** [comment]
Hmm, looks like the app is missing Welcombe Bay too:

https://www.linz.govt.nz/sites/default/files/docs/hydro/tidal-info/tide-tables/maj-ports/csv/Welcombe%20Bay%202016.csv

To be clear, both of these are "major ports", not those for which one needs to calculate the tide offset.

**Comment by robinpaulson** [comment]
Akaroa, too.

https://www.linz.govt.nz/sites/default/files/docs/hydro/tidal-info/tide-tables/maj-ports/csv/Akaroa%202016.csv

**Comment by robinpaulson** [comment]
Sorry, i just saw the updates to the app and realised these are in. Sigh, I'm getting in a tangle. My bad

**Comment by jevonlongdell** [comment]
Have reopened this because Chalreston is missing. Data was in the last lot I got from linz but wasn't read in when making the latest release. Akaroa and Welcombe bay are in but I might have missed others. I'll have a look some time. Ideeally there shouldn't be any "2020" datafiles in  https://github.com/jevonlongdell/nztides/tree/master/tidelookup/txtfiles that aren't listed in ine 22 of https://github.com/jevonlongdell/nztides/blob/master/tidelookup/binaryise_txt_tidetables.py.

Feel free to point out others that are missing.

**Comment by robinpaulson** [comment]
Will do. I used this page:
https://www.linz.govt.nz/sea/tides/tide-predictions

to look up the locations which LINZ provides data for.

**Comment by robinpaulson** [comment]
I didn't find any others missing, closing.
